In [23]:
import numpy as np 
import matplotlib.pyplot as mtp  
import pandas as pd  

In [24]:
df = pd.read_excel(r'D:\MBATech\badm\031020 mt2\badm_mt2.xlsx', sheet_name='Sheet1')

In [25]:
print(df)

    gmat  gpa  work_experience  admitted
0    780  4.0                3         1
1    750  3.9                4         1
2    690  3.3                3         0
3    710  3.7                5         1
4    680  3.9                4         0
5    730  3.7                6         1
6    690  2.3                1         0
7    720  3.3                4         1
8    740  3.3                5         1
9    690  1.7                1         0
10   610  2.7                3         0
11   690  3.7                5         1
12   710  3.7                6         1
13   680  3.3                4         0
14   770  3.3                3         1
15   610  3.0                1         0
16   580  2.7                4         0
17   650  3.7                6         1
18   540  2.7                2         0
19   590  2.3                3         0
20   620  3.3                2         1
21   600  2.0                1         0
22   550  2.3                4         0
23   550  2.7   

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   gmat             40 non-null     int64  
 1   gpa              40 non-null     float64
 2   work_experience  40 non-null     int64  
 3   admitted         40 non-null     int64  
dtypes: float64(1), int64(3)
memory usage: 1.4 KB


In [27]:
x= df.iloc[:, [0,2]].values  
y= df.iloc[:, 3].values  

In [28]:
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.25, random_state=0)  

In [29]:
from sklearn.preprocessing import StandardScaler    
st_x= StandardScaler()    
x_train= st_x.fit_transform(x_train)    
x_test= st_x.transform(x_test)  

# Logistic Regression

In [30]:
#Fitting Logistic Regression to the training set  
from sklearn.linear_model import LogisticRegression  
lr= LogisticRegression(solver='liblinear')  
lr.fit(x_train, y_train)  

LogisticRegression(solver='liblinear')

In [31]:
y_pred= lr.predict(x_test)

In [32]:
import statsmodels.api as sm      
x_train = sm.add_constant(x_train)
lr = sm.OLS(y_train, x_train).fit()
lr.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.755
Model:                            OLS   Adj. R-squared:                  0.737
Method:                 Least Squares   F-statistic:                     41.61
Date:                Sat, 03 Oct 2020   Prob (F-statistic):           5.66e-09
Time:                        08:35:18   Log-Likelihood:               -0.60641
No. Observations:                  30   AIC:                             7.213
Df Residuals:                      27   BIC:                             11.42
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.4667      0.048      9.821      0.000       0.369       0.564
x1             0.2200      0.052      4.205      0.000       0.113       0.327
x2             0.2927      0.052      5.594      0.000       0.185       0.400
==============================================================================
Omnibus:                        2.864   Durbin-Watson:                   1.798
Prob(Omnibus):                  0.239   Jarque-Bera (JB):                1.847
Skew:                          -0.599   Prob(JB):                        0.397
Kurtosis:                       3.210   Cond. No.                         1.56
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [33]:
from sklearn.metrics import confusion_matrix
confusion_matrix=confusion_matrix(y_test,y_pred)
print(confusion_matrix)

[[4 1]
 [1 4]]


In [38]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.80      0.80      0.80         5
           1       0.80      0.80      0.80         5

    accuracy                           0.80        10
   macro avg       0.80      0.80      0.80        10
weighted avg       0.80      0.80      0.80        10



In [37]:
model = LogisticRegression(solver='liblinear', C=10.0, random_state=0)
model.fit(x, y)

LogisticRegression(C=10.0, random_state=0, solver='liblinear')

# Clustering

In [13]:
import warnings
warnings.filterwarnings('ignore')

In [14]:
dataset = pd.read_excel('Badm_Clustering.xlsx') 
dataset

Unnamed: 0   x   y
0            0  25  79
1            1  34  51
2            2  22  53
3            3  27  78
4            4  33  59
5            5  33  74
6            6  31  73
7            7  22  57
8            8  35  69
9            9  34  75
10          10  67  51
11          11  54  32
12          12  57  40
13          13  43  47
14          14  50  53
15          15  57  36
16          16  59  35
17          17  52  58
18          18  65  59
19          19  47  50
20          20  49  25
21          21  48  20
22          22  35  14
23          23  33  12
24          24  44  20
25          25  45   5
26          26  38  29
27          27  43  27
28          28  51   8
29          29  46   7

In [15]:
from sklearn.preprocessing import StandardScaler

In [16]:
scaler = StandardScaler()
scaled_dataset = scaler.fit_transform(dataset[["x", "y"]] )
scaled_dataset[0:5]

array([[-1.46758284,  1.58780564],
       [-0.718533  ,  0.34594648],
       [-1.71726612,  0.43465071],
       [-1.30112732,  1.54345353],
       [-0.80176076,  0.70076338]])

In [17]:
from sklearn.cluster import KMeans
clusters = KMeans(3, random_state=42)
clusters.fit(dataset)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=3, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=42, tol=0.0001, verbose=0)

In [18]:
x = dataset.iloc[:, [2, 2]].values  

In [19]:
dataset["clusterid"] = clusters.labels_

In [20]:
dataset[0:5]

Unnamed: 0   x   y  clusterid
0           0  25  79          0
1           1  34  51          0
2           2  22  53          0
3           3  27  78          0
4           4  33  59          0

In [21]:
clusters.cluster_centers_

array([[ 4.5, 29.6, 66.8],
       [24.5, 43.2, 16.7],
       [14.5, 55.1, 46.1]])

In [22]:
dataset.groupby( 'clusterid' )['x','y'].agg( ["mean",'std'] ).reset_index()

clusterid     x               y           
             mean       std  mean        std
0         0  29.6  5.125102  66.8  10.716550
1         1  43.2  6.033241  16.7   8.718435
2         2  55.1  7.534366  46.1   9.757618