### pg 130 q10

In [1]:
import numpy as np

In [2]:
s1 = np.array([[1,1,1,1]])

In [3]:
s2 = np.array([[-1,1,1,-1]])

In [4]:
s1t=s1.transpose()
s1

array([[1, 1, 1, 1]])

In [5]:
s2t=s2.transpose()
s2

array([[-1,  1,  1, -1]])

In [6]:
w=[]

In [7]:
w1=np.dot(s1t,s1)

In [8]:
w2=np.dot(s2t,s2)

In [9]:
w=w1+w2
w

array([[2, 0, 0, 2],
       [0, 2, 2, 0],
       [0, 2, 2, 0],
       [2, 0, 0, 2]])

#### testing

In [10]:
r = np.dot(s1,w)
r

array([[4, 4, 4, 4]])

In [11]:
ans=[]

In [12]:
#activation function
for i in range(len(r[0])):
    if r[0][i]<0:
        ans.append(-1)
    if r[0][i]>0:
        ans.append(1)
    if r[0][i]==0:
        ans.append(0)

In [13]:
ans

[1, 1, 1, 1]