#### pg 123 q3

In [29]:
import numpy as np

In [30]:
s = np.array([[1,0,0,0],
              [1,1,0,0],
              [0,0,0,1],
              [0,0,1,1]])

In [31]:
t = np.array([[0,1],
              [0,1],
              [1,0],
              [1,0]])

In [32]:
w=np.zeros_like(t)
w

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [33]:
len(t[1])

2

In [34]:
count=0
for ip in range(len(s)):  #input loop
#     print("\n\n")
#     print("ip=",ip)
    for wi in range(len(t)):   #weight iteration loop
#         print("\n")
#         print("wi=",wi)
        for wii in range(len(t[1])):
#             print("wii=",wii)
            count=count+1
#             print(count)
#             print("\n")
            w[wi][wii]=w[wi][wii]+(s[ip][wi]*t[ip][wii])

In [35]:
s[1]

array([1, 1, 0, 0])

In [36]:
w

array([[0, 2],
       [0, 1],
       [1, 0],
       [2, 0]])

In [37]:
r = np.dot(s[1],w)
r

array([0, 3])

In [38]:
ans=[]
for i in range(len(r)):
    if r[i]<0:
        ans.append(-1)
    if r[i]>0:
        ans.append(1)
    if r[i]==0:
        ans.append(0)

In [39]:
ans

[0, 1]

In [43]:
# if ans in t:
#     print("yes")
count=0
for i in range(len(t)):
    if ans[0]==t[i][0] and ans[1]==t[i][1]:
        count=count+1
        print(count)

1
2


In [41]:
if count>0:
    print("yes")

yes
