In [1]:
pip install scikit-fuzzy

In [23]:
import skfuzzy as sf

In [24]:
#Taking 2 Fuzzzy sets
x = {'x1': 0.3, 'x2': 0.7, 'x3': 1}
y = {'y1': 0.4, 'y2': 0.9}

print("The two fuxxy sets are:") 
print("X = "+ str(x))
print("Y = "+ str(y))

The two fuxxy sets are:
X = {'x1': 0.3, 'x2': 0.7, 'x3': 1}
Y = {'y1': 0.4, 'y2': 0.9}


In [25]:
#Extracting the values from dict

X = list(x.values())
Y = list(y.values())
print(X)
print(Y)

[0.3, 0.7, 1]
[0.4, 0.9]


## **Calculating Cartesian Product**

In [26]:
print("The Cartesian Product of the fuzzy sets are:")
sf.fuzzymath.cartprod(X, Y)

The Cartesian Product of the fuzzy sets are:


array([[0.3, 0.3],
       [0.4, 0.7],
       [0.4, 0.9]])

## **Union, Intersection, Complement & Difference operations on Fuzzy sets**


In [12]:
A = dict() 
B = dict() 
Y = dict() 
  
A = {"a": 0.3, "b": 0.7, "c": 0.6, "d": 0.9} 
B = {"a": 0.9, "b": 0.8, "c": 0.4, "d": 0.6} 
  
print('The First Fuzzy Set is :', A) 
print('The Second Fuzzy Set is :', B) 
  
#Union  
for A_key, B_key in zip(A, B): 
    A_value = A[A_key] 
    B_value = B[B_key] 
  
    if A_value > B_value: 
        Y[A_key] = A_value 
    else: 
        Y[B_key] = B_value 
          
print('Fuzzy Set Union is :', Y) 

The First Fuzzy Set is : {'a': 0.3, 'b': 0.7, 'c': 0.6, 'd': 0.9}
The Second Fuzzy Set is : {'a': 0.9, 'b': 0.8, 'c': 0.4, 'd': 0.6}
Fuzzy Set Union is : {'a': 0.9, 'b': 0.8, 'c': 0.6, 'd': 0.9}


In [13]:
#Intersection
for A_key, B_key in zip(A, B): 
    A_value = A[A_key] 
    B_value = B[B_key] 
  
    if A_value < B_value: 
        Y[A_key] = A_value 
    else: 
        Y[B_key] = B_value 
print('Fuzzy Set Intersection is :', Y) 

Fuzzy Set Intersection is : {'a': 0.3, 'b': 0.7, 'c': 0.4, 'd': 0.6}


In [14]:
#Complement
H = {"a": 0.2, "b": 0.3, "c": 0.6, "d": 0.6} 
  
print('The Fuzzy Set is :', H) 
  
  
for H_key in H: 
   Y[H_key]= 1-H[H_key] 
          
print('Fuzzy Set Complement is :', Y) 

The Fuzzy Set is : {'a': 0.2, 'b': 0.3, 'c': 0.6, 'd': 0.6}
Fuzzy Set Complement is : {'a': 0.8, 'b': 0.7, 'c': 0.4, 'd': 0.4}


In [19]:
#Difference
A = dict() 
B = dict() 
Y = dict() 
  
A = {"a": 0.2, "b": 0.3, "c": 0.6, "d": 0.6} 
B = {"a": 0.7, "b": 0.1, "c": 0.4, "d": 0.5} 
  
for A_key, B_key in zip(A, B): 
    A_value = A[A_key] 
    B_value = B[B_key] 
    B_value = 1 - B_value 
  
    if A_value < B_value: 
        Y[A_key] = A_value 
    else: 
        Y[B_key] = B_value 
          
print('Fuzzy Set Difference is :', Y) 

The First Fuzzy Set is : {'a': 0.2, 'b': 0.3, 'c': 0.6, 'd': 0.6}
The Second Fuzzy Set is : {'a': 0.7, 'b': 0.1, 'c': 0.4, 'd': 0.5}
Fuzzy Set Difference is : {'a': 0.2, 'b': 0.3, 'c': 0.6, 'd': 0.5}


## **Min-Max Composition and Max-Product** 

In [21]:
import numpy as np

# Max-Min Composition 
def maxMin(x, y):
    z = []
    for x1 in x:
        for y1 in y.T:
            z.append(max(np.minimum(x1, y1)))
    return np.array(z).reshape((x.shape[0], y.shape[1]))

# Max-Product Composition 
def maxProduct(x, y):
    z = []
    for x1 in x:
        for y1 in y.T:
            z.append(max(np.multiply(x1, y1)))
    return np.array(z).reshape((x.shape[0], y.shape[1]))

# Taking 3 arrays for the example
arr1 = np.array([[1, 0, .7], [.3, .2, 0], [0, .5, 1]])
arr2 = np.array([[.6, .6, 0], [0, .6, .1], [0, .1, 0]])
arr3 = np.array([[1, 0, .7], [0, 1, 0], [.7, 0, 1]])

print ("Max-Min for 1st and 2nd array :\n" + str(maxMin(arr1, arr2)) + "\n")
print ("Max-Product for 1st and 2nd array :\n" + str(maxProduct(arr1, arr2)) + "\n\n")

print ("Max-Min for 1st and 3rd array :\n" + str(maxMin(arr1, arr3)) + "\n")
print ("Max-Product for 1st and 3rd array :\n" + str(maxProduct(arr1, arr3)) + "\n\n")

print ("Max-Min for the 3 arrays :\n" + str(maxMin(arr1, maxMin(arr2, arr3))) + "\n")
print ("Max-Product for the 3 arrays :\n" + str(maxProduct(arr1, maxProduct(arr2, arr3))) + "\n\n")


Max-Min for 1st and 2nd array :
[[0.6 0.6 0. ]
 [0.3 0.3 0.1]
 [0.  0.5 0.1]]

Max-Product for 1st and 2nd array :
[[0.6  0.6  0.  ]
 [0.18 0.18 0.02]
 [0.   0.3  0.05]]


Max-Min for 1st and 3rd array :
[[1.  0.  0.7]
 [0.3 0.2 0.3]
 [0.7 0.5 1. ]]

Max-Product for 1st and 3rd array :
[[1.   0.   0.7 ]
 [0.3  0.2  0.21]
 [0.7  0.5  1.  ]]


Max-Min for the 3 arrays :
[[0.6 0.6 0.6]
 [0.3 0.3 0.3]
 [0.1 0.5 0.1]]

Max-Product for the 3 arrays :
[[0.6   0.6   0.42 ]
 [0.18  0.18  0.126]
 [0.035 0.3   0.05 ]]


